### ISSUE TITLE
Alternate temperature interpretation

### ISSUE THREAD

**Issue by sandeen** [albertnis/fujitsu-ar-ry13-ir-codes#1]
Not an issue per se, just the easiest way to comment I think?  :)

If you reverse the bits in the 2nd nibble of the temperature byte, the mapping is a bit less random.
It also jives with [this PDF](http://old.ercoupe.com/audio/FujitsuIR.pdf) that has been floating around for a while (modulo the weird bit-reverse)

```
 C  F      fw   hex     rev     hex
19 66 0000 1100 0x0c    0011    0x03
20 68 0000 0010 0x02    0100    0x04
21 70 0000 1010 0x0A    0101    0x05
22 72 0000 0110 0x06    0110    0x06
23 74 0000 1110 ...     0111    0x07
24 76 0000 0001         1000    0x08
25 78 0000 1001         1001    0x09
26 80 0000 0101         1010    0x0A
27 82 0000 1101         1011    0x0B
28 84 0000 0011         1100    0x0C
29 86 0000 1011         1101    0x0D
30 88 0000 0111         1110    0x0E
```
Thanks for writing this all down!  Checking out my AR-RED1U remote to see if it's the same.

**Comment by albertnis** [comment]
Brilliant! Thank you for this tidbit - I hadn't thought of it like that. And yeah, those temperature nibbles did have me scratching my head a bit...

I'll incorporate this information into the README by doing the following:
* Add Farenheit to the temperature table
* Add a comment explaining the nibble values

I'll leave this open as an issue and close it with a corresponding PR.

**Comment by sandeen** [comment]
Cool - and as for the Farenheit question in the readme, I think it's only a matter of display on the remote, I don't think commands change at all (mine is in F not C).

**Comment by albertnis** [comment]
Sounds about right. Didn't include Farenheit mostly because I wasn't sure what the exact °F values were (as displayed on the remote).
