### ISSUE TITLE
AR-RY13 IR Codes

### ISSUE THREAD

**Issue by wsc96** [albertnis/fujitsu-ar-ry13-ir-codes#4]
Hi, 

I found your YouTube video showing you using this remote with Home Assistant. Are you able to share the codes you generated? I'm using smartir, broadlink ar-ay13 also.

Thanks!

**Comment by albertnis** [comment]
Hi there and sorry for the delayed response. I'm unsure what the exact codes were, but I do know they were generated by the [server file](https://github.com/albertnis/fujitsu-ar-ry13-ir-codes/blob/3f159249e674318561166f4cdc15d7db04e68f25/src-js/server.js). The home assistant instance I am accessing in the video is set up with node red in such a way that changing the Home Assistant state will call the server with the desired heatpump state to retrieve a Broadlink code, then send that Broadlink code to the IR blaster.

The codes I was sending in the video would have looked something like this, which is the output from `curl "http://localhost:8080/broadlink?tempC=18&mode=heat&fanSpeed=Quiet&swing=Off&powerOn=0"`:

```
JgAGAWg0DQ0NDQ0mDQ0NJg0NDQ0NDQ0mDSYNDQ0NDQ0NJg0mDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NJg0NDQ0NDQ0NDQ0NDQ0NDSYNDQ0NDQ0NDQ0mDSYNJg0mDSYNJg0mDSYNDQ0NDSYNDQ0NDQ0NDQ0NDQ0NDQ0NDSYNJg0NDQ0NDQ0NDQ0NDQ0NDSYNDQ0NDQ0NDQ0mDQ0NDQ0NDQ0NDQ0NDQ0NJg0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDSYNDQ0NDQ0NDQ0NDSYNDQ0NDQ0NJg3/DQUAAA==
```

Please let me know whether that answers your question. I am closing the issue assuming it does, but I can reopen it if you have more questions.

**Comment by wsc96** [comment]
Yes all good now thanks. I went through and generated all the codes. Thanks for sharing your work on this.
